Unbreak mocha.js
Changes introduced in 55a91ea causes failing tests in Mocha to crash the runner with the following error:
```
node_modules/protractor/lib/frameworks/mocha.js:85
          errorMsg: test.err.message,
                            ^
TypeError: Cannot read property 'message' of undefined
```

This is because you are erroneously attempting to retrieve the error from the `test` object in Mocha's `fail` event. The `fail` event actually delivers two separate arguments, the test that failed and the error with which the test failed. This corrects the error.