docs(element): Fix docs for #896 (clear() and sendKeys())
Commit 3c0e727 (PR #896) allowed chaining of actions (i.e.
`element(By.x).clear().sendKeys('abc)`). Since then, the return type of
`clear()` and `sendKeys()` is not longer a `Promise<void>`, but the
WebElement itself.

This commit fixes the docs.

It will allow typings for selenium-webdriver to be corrected. Until now,
TypeScript complains with:

    error TS2339: Property 'sendKeys' does not exist on type 'Promise<void>'.